plugins {
    id 'eclipse'
    id 'idea'
    id 'java-library'
    id 'maven-publish'
    id 'net.neoforged.moddev' version '2.0.103'
    id 'io.github.goooler.shadow' version '8.1.8'
}

group = 'org.lovetropics.lib'
base {
    archivesName = 'LTLib'
}

def env = System.getenv()

if (env.GITHUB_RUN_NUMBER) {
    version = "$mod_version.${env.GITHUB_RUN_NUMBER}"
} else {
    version = "$mod_version.0-SNAPSHOT"
}

java.toolchain.languageVersion = JavaLanguageVersion.of(21)

neoForge {
    version = project.neo_version

    parchment {
        minecraftVersion = minecraft_version
        mappingsVersion = parchment_version
    }

    addModdingDependenciesTo sourceSets.test

    mods {
        "${project.mod_id}" {
            sourceSet sourceSets.main
        }
        "${project.mod_id}_test" {
            sourceSet sourceSets.main
            sourceSet sourceSets.test
        }
    }

    runs {
        client {
            client()
            loadedMods = [mods."${mod_id}"]

            programArguments.addAll '--username', '"Dev###"'
            systemProperty 'neoforge.enabledGameTestNamespaces', project.mod_id
        }

        server {
            server()
            loadedMods = [mods."${mod_id}"]

            programArgument '--nogui'
            systemProperty 'neoforge.enabledGameTestNamespaces', project.mod_id
        }

        data {
            clientData()
            loadedMods = [mods."${mod_id}"]

            programArguments.addAll '--mod', project.mod_id, '--all', '--output', file('src/generated/resources/').getAbsolutePath(), '--existing', file('src/main/resources/').getAbsolutePath()
        }

        configureEach {
            logLevel = org.slf4j.event.Level.INFO
            ideName = "${project.name} - ${ideName.get()}"
        }
    }
}

sourceSets.main.resources {
    srcDir 'src/generated/resources'
}

repositories {
    mavenLocal()
}

dependencies {
    shadow('io.netty:netty-codec-http:4.1.118.Final') {
        transitive = false
    }
}

tasks.named('jar', Jar).configure {
    manifest {
        attributes([
            "FMLModType": "GAMELIBRARY",
            "Specification-Title": "ltlib",
            "Specification-Vendor": "lovetropics",
            "Specification-Version": "1", // We are version 1 of ourselves
            "Implementation-Title": project.name,
            "Implementation-Version": "${version}",
            "Implementation-Vendor" :"lovetropics",
            "Implementation-Timestamp": new Date().format("yyyy-MM-dd'T'HH:mm:ssZ")
        ])
    }

    archiveClassifier = 'slim'
}

tasks.register('sourceJar', Jar) {
    dependsOn classes
    archiveClassifier = 'sources'
    from sourceSets.main.java
}

configurations {
    shadow
    implementation.extendsFrom shadow
}

shadowJar {
    configurations = [project.configurations.shadow]
    archiveClassifier = ''

    ['http', 'rtsp', 'spdy'].forEach {
        relocate "io.netty.handler.codec.$it", "com.lovetropics.lib.repack.io.netty.handler.codec.$it"
    }
}

publishing {
    publications {
        mavenJava(MavenPublication) {
            artifact shadowJar
            artifact sourceJar
        }
    }

    repositories {
        if (env.MAVEN_URL) {
            maven {
                credentials {
                    username env.MAVEN_USERNAME
                    password env.MAVEN_PASSWORD
                }
                url env.MAVEN_URL
            }
        } else {
            println("Warning: no MAVEN_URL specified, publishing to mavenLocal")
            mavenLocal()
        }
    }
}
